const Constants = {
    REQUEST_STARTED: 'REQUEST_STARTED',
    REQUEST_SUCCESSFUL: 'REQUEST_SUCCESSFUL',
    REQUEST_FAILED : 'REQUEST_FAILED',
    RESET_REQUEST : 'RESET_REQUEST',
    REMOVE_TODO : 'REMOVE_TODO',
    ADD_TODO : 'ADD_TODO',
    CLEAR_COMPLETED : 'CLEAR_COMPLETED',
    CHANGE_COMPLETED : 'CHANGE_COMPLETED',
};

export default Constants;